version: '3.9'

services:
  mongo:
    image: mongo:6.0
    container_name: bluegreen-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: bluegreen-backend
    restart: unless-stopped
    ports:
      - '3003:3003'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/bluegreen
    depends_on:
      - mongo

  frontend-blue:
    build:
      context: ./frontend-blue
    container_name: bluegreen-frontend-blue
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    depends_on:
      - backend

  frontend-green:
    build:
      context: ./frontend-green
    container_name: bluegreen-frontend-green
    restart: unless-stopped
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
    depends_on:
      - backend

volumes:
  mongo-data:
