apiVersion: v1
kind: ConfigMap
metadata:
  name: bluegreen-config
  namespace: bluegreen
data:
  MONGO_URI: "mongodb://admin:mongopass@mongodb-service:27017/bluegreen?authSource=admin"
  BACKEND_URL: "http://backend-service:5000"
  NODE_ENV: "production"
