apiVersion: v1
kind: Secret
metadata:
  name: bluegreen-secrets
  namespace: bluegreen
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "mongopass"
  MONGO_URI: "mongodb://admin:mongopass@mongodb-service:27017/bluegreen?authSource=admin"
